modLoader = "javafml"
loaderVersion = "[9,)"
issueTrackerURL = "https://github.com/Micalobia/Full-Slabs/issues"
license = "MIT"

[[mods]]
modId = "fullslabs"
version = "${version}"
displayName = "FullSlabs"
authors = "Micalobia"
description = '''
This adds vertical and mixed slabs into the game!
'''
logoFile = "assets/fullslabs/icon.png"

[[dependencies.fullslabs]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fullslabs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fullslabs]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "fullslabs.mixins.json"
